### ISSUE TITLE
Duplicated mapping key

### ISSUE THREAD

**Issue by douglasanunciacao** [apigee/streetcarts#3]
In the line 237 of the file streetcarts/specs/openapi/streetcarts.yaml there is a duplicated key "description":
```
uuid:
  type: string
  description: ID of the food cart.
  description: Name of the food cart.
```
